apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
  annotations:
    description: "Standard CephFS volume"

    storageclass.kubernetes.io/is-default-class: {{ .Values.cephfsManilaCSI.isDefaultStorageClass | default false | toString | quote }}

    # CIPAAS-569: the following annotations are used by an OPA rule
    # to manipulate properties of PVs and PVCs using the cephfs storageclass

    # CIPAAS-549 always set all access modes to cephfs PV and PVC
    # (cephfs manila provisioner only sets the modes specified in PVC, which default to RWO
    # and thus does not work with rolling deployments)
    pvc.opa.openshift.ch/add-access-modes: |
      - ReadWriteMany
      - ReadWriteOnce
      - ReadOnlyMany

    # CIPAAS-451: cephfs PVs should be backed up
    pv.opa.openshift.ch/set-default-labels: |
      backup-cephfs-volumes.ch/backup: "true"


# manila-csi helm chart creates an instance for each share protocol we have enabled
# check with `oc get csidrivers.storage.k8s.io` the name of the csi-driver deployed
provisioner: cephfs.{{ template "cephfscsi.drivername" . }}
parameters:
  # Manila share type
  type: {{ .Values.cephfsManilaCSI.sharesType }}

  # The secrets have to contain user and/or Ceph admin credentials.
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.cephfsManilaCSI.osSecretName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.cephfsManilaCSI.osSecretName }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Values.namespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ .Values.cephfsManilaCSI.osSecretName }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.namespace }}
  cephfs-mounter: kernel
  # Do not update file access time, saves some operations on the network filesystem
  # See https://github.com/ceph/ceph-csi/issues/1506
  fuseMountOptions: noatime
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs-no-backup
  annotations:
    description: "CephFS persistent volume without automatic backup. It is not possible to recover a previous state of the volume. Appropriate for non-critical, frequently-changing or rolling data."

    # CIPAAS-569: the following annotations are used by an OPA rule
    # to manipulate properties of PVs and PVCs using the cephfs-no-backup storageclass

    # CIPAAS-549 always set all access modes to cephfs-no-backup PV and PVC
    # (cephfs manila provisioner only sets the modes specified in PVC, which default to RWO
    # and thus does not work with rolling deployments)
    pvc.opa.openshift.ch/add-access-modes: |
      - ReadWriteMany
      - ReadWriteOnce
      - ReadOnlyMany

# manila-csi helm chart creates an instance for each share protocol we have enabled
# check with `oc get csidrivers.storage.k8s.io` the name of the csi-driver deployed
provisioner: cephfs.{{ template "cephfscsi.drivername" . }}
parameters:
  # Manila share type
  type: {{ .Values.cephfsManilaCSI.sharesType }}

  # The secrets have to contain user and/or Ceph admin credentials.
  csi.storage.k8s.io/provisioner-secret-name: {{ .Values.cephfsManilaCSI.osSecretName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Values.namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ .Values.cephfsManilaCSI.osSecretName }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Values.namespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ .Values.cephfsManilaCSI.osSecretName }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Values.namespace }}
  cephfs-mounter: kernel
  # Do not update file access time, saves some operations on the network filesystem
  # See https://github.com/ceph/ceph-csi/issues/1506
  fuseMountOptions: noatime
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
