apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cephfs-csi-driver
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace | quote }}
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: {{ .Values.cephfsCSIDriver.repoURL }}
    chart: ceph-csi-cephfs
    targetRevision: {{ .Values.cephfsCSIDriver.targetRevision | quote }}
    helm:
      values: |
        ##
        ## Default values for openshift-cephfs csi driver
        ## This is a YAML-formatted file.
        ## Declare variables to be passed into your templates.
        ##

        # We decided to add the clusterName to the driverName as we currently do not have the possibility of distinguish PVCs created for other clusters
        # Once this issue https://github.com/kubernetes/cloud-provider-openstack/issues/1280 is implemented, we will be able to remove this part and really
        # in adding specific metadata for each manila share
        driverName: {{ template "cephfscsi.drivername" . }}

        serviceAccounts:
          nodeplugin:
            # Specifies whether a ServiceAccount should be created
            create: false
            # The name of the ServiceAccount to use.
            # We explicitly configure this SA to create the serviceAccounts with this exact name.
            # Otherwise, if for some reason upstream Helm chart decide to change the default SA name it will stop working.
            name: manila-csi-openstack-manila-csi-nodeplugin
          provisioner:
            # Specifies whether a ServiceAccount should be created
            create: true
            # The name of the ServiceAccount to use.
            # We explicitly configure this SA to create the serviceAccounts with this exact name.
            # Otherwise, if for some reason upstream Helm chart decide to change the default SA name it will stop working.
            name: cephfs-csi-driver-ceph-csi-cephfs-provisioner

        nodeplugin:
          nodeSelector:
{{ toYaml .Values.cephfsCSIDriver.nodePlugin.nodeSelector | indent 12 }}

        provisioner:
          nodeSelector:
{{ toYaml .Values.cephfsCSIDriver.provisioner.nodeSelector | indent 12 }}

        ##
        ## End of additional openshift-cephfs csi driver resource settings.
        ##
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
