apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Manila provisioner credentials to access to the OpenStack API
  name: {{ .Values.cephfsManilaCSI.osSecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  os-applicationCredentialID:     {{ .Values.global.openstack.credentialId     | b64enc }}
  os-applicationCredentialSecret: {{ .Values.global.openstack.credentialSecret | b64enc }}
  os-authURL:                     {{ .Values.global.openstack.authURL          | b64enc }}
  os-region:                      {{ .Values.global.openstack.regionName       | b64enc }}
