apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cephfs-opa-policy
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace | quote }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: {{ .Values.global.opa.source.repoURL }}
    targetRevision: {{ .Values.global.opa.source.targetRevision | quote }}
    helm:
      values: |
        opa:
          argoCDApplicationNamespace: {{ .Release.Namespace }}

          admissionControllerRules:
            # for storageclass-initialize-pv-pvc
            - apiGroups: [""]
              apiVersions: ["*"]
              operations:
              - CREATE
              resources:
              - "persistentvolumeclaims"
              - "persistentvolumes"

          mgmtReplicate:
            cluster:
              - storage.k8s.io/v1/storageclasses

        opaRules:
        # Load all the .rego files inside opa-rules as configMaps so that later they will be
        # loaded/compiled by the OPA
{{ range $path, $bytes := .Files.Glob "opa-rules/*.rego" }}
          - name: {{ base $path }}
            data: |
{{ ($.Files.Get $path) . | indent 14 }}
{{ end }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
