apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'grant all privileges to the Cephfs CSI driver and Manila volume provisioner.'
  name: cephfs-csi
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Values.namespace }}:cephfs-csi-driver-ceph-csi-cephfs-provisioner
- system:serviceaccount:{{ .Values.namespace }}:manila-csi-openstack-manila-csi-controllerplugin
- system:serviceaccount:{{ .Values.namespace }}:manila-csi-openstack-manila-csi-nodeplugin
volumes:
- '*'